baseURL = "https://hariss-notes.mashkarharis.online/"
languageCode = "en-us"
title = "Haris's Notes"
theme = "hugo-book"
params.BookTheme = "light"
googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'