googleAnalytics = "G-92Z0K9S64H"
baseURL = "https://hariss-notes.mashkarharis.online/"
languageCode = "en-us"
title = "Haris's Notes"
theme = "hugo-book"
params.BookTheme = "light"
googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
